vich_uploader :
    db_driver : orm

    mappings :
        proprietes:
            uri_prefix: '%app.path.proprietes%'
            upload_destination: '%kernel.project_dir%/public%app.path.proprietes%'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
